### ISSUE TITLE
Support (Open)WebStart

### ISSUE THREAD

**Issue by hendrikebbers** [tsaglam/Carcassonne#2]
Hi,

very cool project 👍 
To make it more easy for non technical people to use you can provide a JNLP based application that can be started by using [OpenWebStart](https://openwebstart.com) / [Github Repo](https://github.com/karakun/OpenWebStart). By doing so the user do not need to know how to get and install a Java Runtime and how to start a JAR file.

**Comment by tsaglam** [comment]
Thanks for the input, that is actually a great idea!

**Comment by tsaglam** [comment]
Now supported with [v1.7]( https://github.com/tsaglam/Carcassonne/releases/tag/v1.7)!
