### ISSUE TITLE
Nonclickable UI on nonstandard TileType Size

### ISSUE THREAD

**Issue by sanoy1997** [tsaglam/Carcassonne#5]
![grafik](https://user-images.githubusercontent.com/85501350/148942666-7f9780fb-6112-4e90-9804-b826e615448d.png)
if the number of different tile types is changed it is possible that the ui doesnt allow the user to click the button to accept a new configuration, as it is not visible on screen.
This currently only applies to people who are fumbling around in the code, but based on comments i assume it should be possible later for users to add custom tiles. 
In that situation the UI should always be clickable

**Comment by tsaglam** [comment]
This is not a bug in the UI, that is just an effect of not updating the layout of the view when adding more tiles.
Just adapt the corresponding UI layout constants in the class:
https://github.com/tsaglam/Carcassonne/blob/7c0a0f83a5451618745ab300ae5a372efbba3541/src/main/java/carcassonne/view/tertiary/TileDistributionView.java#L39-L40

**Comment by sanoy1997** [comment]
oh nice, i missed them somehow

**Comment by tsaglam** [comment]
Closed, as updating the corresponding UI layout's dimensions is required when adding more tiles.
